Final/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    # path('online-courses/', include('onlineCourses.urls'))
]

base/urls.py
from django.urls import path
from . import views

app_name="base"

urlpatterns = [
    path(route='', view=views.IndexView.as_view(), name="index"),
    path('logout/', views.logout_request, name='logout'),
    path('login/', views.login_request, name='login'),
    path('submit-exam/', views.submit_exam, name='submit_exam'),
    path('registration/', views.registration_request, name='registration'),
    path('course/<str:course_id>/', view=views.CourseDetailsView.as_view(), name='course_detail'),
    path('exam/<str:exam_id>/', view=views.ExamDetailsView.as_view(), name='exam_detail'),
    path('exam/grades/<str:exam_id>', view=views.GradesView.as_view(), name='grades'),
]

base/models.py
from django.db import models
from users.models import User
import uuid

# Create your models here.
class Course(models.Model):
    id = models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=200, blank=True, null=True, default=None)
    def __str__(self):
        return self.title

class Exam(models.Model):
    id = models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)

    def __str__(self):
        return self.title
    
class Question(models.Model):
    id = models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)

    def __str__(self):
        return self.text

class Choice(models.Model):
    id = models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    is_correct = models.BooleanField(default=False)
    
    def __str__(self):
      return f"{self.text} - {self.id}"

class Submission(models.Model):
    id = models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    user_name = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user_name} - {self.question.text}: {self.choice.text}"

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import uuid


class User(AbstractUser):
    id = models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)
    username = models.CharField(unique=True, max_length=100, default="", blank=True, null=True)
    email = models.EmailField(
        max_length=500)
    
    name = models.CharField(max_length=100, default="", blank=True, null=True)
    lastname = models.CharField(max_length=100, default="", blank=True, null=True)

    # Add your custom fields here
    def __str__(self):
      return self.email

base/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from users.models import User
from .models import Course, Question, Choice, Exam, Submission
from django.contrib.auth import login, authenticate, logout
from django.http import HttpResponse

class GradesView(View):
  def get(self, request, exam_id):
    is_correct_count = 0
    total_count = 0


    user = request.user
    user_query = User.objects.get(id=user.id)
    exam_query = Exam.objects.get(id=exam_id)

    submission_query = Submission.objects.filter(question__exam=exam_query, user_name=user_query)

    for submission in submission_query:
      if submission.choice.is_correct:
        is_correct_count += 1

      total_count += 1
      

    if total_count > 0:
        percentage_correct = (is_correct_count / total_count) * 100
    else:
        percentage_correct = 0

    context = {"answers": submission_query, "percentage": percentage_correct }
    return render(request, 'grades.html', context)

class ExamDetailsView(View):
  def get(self, request, exam_id):

    exam_query = Exam.objects.get(id=exam_id)

    # Get the question object using its ID
    course = get_object_or_404(Course, id=exam_query.course.id)
    # Retrieve the related choices for the question
    questions = Question.objects.filter(exam__course=course)

    context = { 'questions': questions }
    # print(exam_query)
    # print(course)
    # print(questions)
    # print(context)
    # print(context, "<-------------- questions")

    return render(request, 'exam_details.html', context)

# Create your views here.
class CourseDetailsView(View):
  def get(self, request, course_id):
    # exam_id = request.GET.get('id')
    # print(exam_id)
    course_query = Course.objects.get(id=course_id)
    exams_query = Exam.objects.filter(course=course_query)
    # print(questions)

    # choices = []
    # for question in questions: 
    #   choice = Choice.objects.get(question=question)
    #   choices.append({ "value": choice.text, "for": question.id })

    context = {
       "course": course_query,
       "exams": exams_query
    }

    # print(context)
    # return HttpResponse(f"Exam ID: {exam_id}")
    return render(request, 'course_details.html', context)
  
  def post(self, request):
    pass

class IndexView(View):
  def get(self, request):
    courses = Course.objects.all()
    context = {
      "courses_list": courses
    }
    return render(request, 'index.html', context)
  
  def post(self, request):
    pass

def submit_exam(request):
  user = request.user
  if request.method == "POST":
    post_data = request.POST.copy()
    post_data.pop('csrfmiddlewaretoken', None)
    # print(post_data, " <-------- Post Values")

    for key, value in post_data.items():
      question_query = Question.objects.get(id=key)
      choice_query = Choice.objects.get(id=value)
      user_query = User.objects.get(id=user.id)
      # print(key, value, " <-------- Post Values")

      try:
        sumption = Submission.objects.get(question=question_query, user_name=user_query)
        
        sumption.question=question_query
        sumption.choice=choice_query
        sumption.user_name=user_query
        sumption.save()
      
      except Submission.DoesNotExist:
          Submission.objects.create(question=question_query, choice=choice_query, user_name=user_query)
         
    return redirect('/?information=Answers saved!')
      # print(f"Key: {key}, Value: {value}")
    # new_dict = {key: value for key, value in request.POST.items() if key != 'csrfmiddlewaretoken'}

def login_request(request):
    context = {}

    # print(request.method)
    if request.method == "POST":

        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)
        if user is not None:

            login(request, user)
            return redirect("base:index")
        else:
            return redirect("base:index")
    else:
        return redirect("base:index")
    
def login_request(request):
    context = {}

    # print(request.method)
    if request.method == "POST":

        username = request.POST['username']
        password = request.POST['password']


        user = authenticate(username=username, password=password)
        if user is not None:

            login(request, user)
            return redirect("base:index")
        else:
            return redirect("base:index")
    else:
        return redirect("base:exam")

def registration_request(request):
  if request.method == 'POST':
    username = request.POST["username"]
    password = request.POST["password"]

    user = User.objects.create_user(username=username, password=password)
    login(request, user)
    return redirect("base:index")

def logout_request(request):
    # Get the user object based on session id in request
    print("Log out the user `{}`".format(request.user.username))
    # Logout user in the request
    logout(request)
    # Redirect user back to course list view
    return redirect("base:index")

users/views.py
from django.shortcuts import render

# Create your views here.

base/templates/course_details.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Courses </title>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body>
    <nav class="bg-gray-800">
      <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
        <div class="relative flex h-16 items-center justify-between">
          <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
            <div class="flex flex-shrink-0 items-center">
            </div>
            <div class="hidden sm:ml-6 sm:block">
              <div class="flex space-x-4">
                <a href="{% url 'base:index' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">Courses</a>
                {% comment %} {% if user.is_authenticated %}
                <a href="{% url 'base:grades' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">Grades</a>
                {% endif %} {% endcomment %}
                {% comment %} <a href="#" class="bg-gray-900 text-white rounded-md px-3 py-2 text-sm font-medium" aria-current="page">Grades</a> {% endcomment %}
              </div>
            </div>
          </div>
          <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
            {% if user.is_authenticated %}
              <div class="flex justify-center align-center items-center text-gray-300 rounded-md px-3 py-2 text-sm font-medium">
                <div>
                  <p class="p-1">Pablo Cabrera</p>
                  <a href="{% url 'base:logout' %}" class="p-1 cursor-pointer hover:bg-gray-700 hover:text-white">Logout</a>
                  {% comment %} <a href="{% url 'courses:logout' %}">Logout</a> {% endcomment %}
                </div>
                {% comment %} <button type="button" class="relative flex rounded-full bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800" id="user-menu-button" aria-expanded="false" aria-haspopup="true"> {% endcomment %}
                  <img class="h-8 w-8 rounded-full" src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.pngmart.com%2Ffiles%2F22%2FUser-Avatar-Profile-PNG-Isolated-Transparent-HD-Photo.png&f=1&nofb=1&ipt=0bdf7aac280d713f0c4c8e99ca36ca2159a4adab7360de007ffe1e3180c0a029&ipo=images" alt="">
                {% comment %} </button> {% endcomment %}
              </div>
            {% else %}
              <div>
                <form action="{% url 'base:login' %}" method="POST" class="flex text-white text-sm">
                  {% csrf_token %}
                  <div class="flex justify-center align-center items-center">
                    <label for="first-name" class="text-sm font-semibold p-1">User Name</label>
                    <input
                      type="text"
                      name="username"
                      id="username"
                      class="rounded-md border-0 p-1 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600"
                    >
                  </div>
                  <div class="flex justify-center align-center items-center">
                    <label for="first-name" class="text-sm font-semibold p-1">Password</label>
                    <input
                      type="password"
                      name="password"
                      id="password"
                      class="rounded-md border-0 p-1 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600"
                    >
                  </div>
                  <form class="flex justify-center align-center items-center p-1">
                    <button type="submit" class="w-full rounded-md bg-indigo-600 px-3.5 py-2.5 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Log in</button>
                  </form>
                </form>
              </div>
            {% endif %}
            </div>
          </div>
        </div>
      </div>
    </nav>
    <main>
      <div
        class="w-screen h-[40vh]"
        style="
          background-image: url('https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fvistapointe.net%2Fimages%2Fprogramming-2.jpg&f=1&nofb=1&ipt=32b8f1efbc0db3cb760971341ef483b4628b9d93185f48b9eea71224fb05b8b5&ipo=images');
          background-position: center;
          background-size: cover;
          background-repeat: no-repeat;
        ">
          <div class="w-full h-full bg-[rgba(0,0,0,0.3)]" />
      </div>
      <div class="w-8/12 ml-auto mr-auto pt-10">
        <div class="flex justify-left align-middle items-center pt-4 pb-4">
          <div onclick="goBack()" class="flex justify-center align-middle items-center hover:underline cursor-pointer">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8"/>
            </svg>
            <p> Regresar </p>
          </div>
        </div>
        <h2 class="text-3xl font-bold">
          {{ course.title }}
        </h2>
        <p>{{ course.description }}</p>
        
        <h2 class="text-2xl font-bold mt-10">
          Exams List
        </h2>
        <hr />
        {% if exams %}
        <ul role="list" class="divide-y divide-gray-100 shadow-md p-10 rounded-md">
          {% for exam in exams  %}
          <li class="flex justify-between gap-x-6 py-5">
            <div class="flex min-w-0 gap-x-4">
              <img class="h-12 w-12 flex-none rounded-full bg-gray-50" src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ficon-library.com%2Fimages%2Fcourses-icon%2Fcourses-icon-27.jpg&f=1&nofb=1&ipt=4ae21b8868505c06482380b1845bacb474e463240f887108389fcefef86d6ecb&ipo=images" alt="">
              <div class="flex justify-center align-middle items-center">
                <p class="text-sm font-semibold leading-6 text-gray-900"> {{ exam.title }} </p>
              </div>
            </div>
            <div class="flex justify-center align-middle items-center flex-col">
              {% if user.is_authenticated %}
              {% comment %} href="{% url 'base:exam_detail' %}?id={{ course.id }}" {% endcomment %}
              <div class="p-2">
                <a
                  href="{% url 'base:exam_detail' exam.id %}"
                  class="w-full rounded-md bg-indigo-600 p-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
                >Take exam</a>
              </div>
              <div class="p-2">
                <a
                  href="{% url 'base:grades' exam.id %}"
                  class="w-full rounded-md bg-indigo-600 p-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
                >View results</a>
              </div>
              {% else %}
                <p class="text-xs text-red-800"> ( You must log in first ) </p>
                <div class="p-1">
                  <button disabled="disabled" class="bg-gray-300 w-full rounded-md px-3.5 py-2.5 text-center text-sm font-semibold text-white shadow-sm">Take exam</button>
                </div>
                <div class="p-1">
                  <button disabled="disabled" class="bg-gray-300 w-full rounded-md px-3.5 py-2.5 text-center text-sm font-semibold text-white shadow-sm">View results</button>
                </div>
              {% endif %}
            </div>
          </li>
          {% endfor %}
        </ul>
        {% else %}
        <div class="w-full flex justify-center align-middle items-center">
          <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative w-full" role="alert">
            <strong class="font-bold text-center">Ups...!</strong> <br />
            <span class="block sm:inline text-center">There are no exams available</span>
          </div>
        </div>
        {% endif %}
      </div>
    </main>
    <script>
    function goBack() {
        window.history.back();
    }
    </script>
  </body>
</html>

base/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title> Courses </title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
  <nav class="bg-gray-800">
    <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
      <div class="relative flex h-16 items-center justify-between">
        <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
          <div class="flex flex-shrink-0 items-center">
          </div>
          <div class="hidden sm:ml-6 sm:block">
            <div class="flex space-x-4">
              <a href="{% url 'base:index' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">Courses</a>
              {% comment %} {% if user.is_authenticated %}
              <a href="{% url 'base:grades' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">Grades</a>
              {% endif %} {% endcomment %}
              {% comment %} <a href="#" class="bg-gray-900 text-white rounded-md px-3 py-2 text-sm font-medium" aria-current="page">Grades</a> {% endcomment %}
            </div>
          </div>
        </div>
        <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
          {% if user.is_authenticated %}
            <div class="flex justify-center align-center items-center text-gray-300 rounded-md px-3 py-2 text-sm font-medium">
              <div>
                <p class="p-1">Pablo Cabrera</p>
                <a href="{% url 'base:logout' %}" class="p-1 cursor-pointer hover:bg-gray-700 hover:text-white">Logout</a>
                {% comment %} <a href="{% url 'courses:logout' %}">Logout</a> {% endcomment %}
              </div>
              {% comment %} <button type="button" class="relative flex rounded-full bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800" id="user-menu-button" aria-expanded="false" aria-haspopup="true"> {% endcomment %}
                <img class="h-8 w-8 rounded-full" src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.pngmart.com%2Ffiles%2F22%2FUser-Avatar-Profile-PNG-Isolated-Transparent-HD-Photo.png&f=1&nofb=1&ipt=0bdf7aac280d713f0c4c8e99ca36ca2159a4adab7360de007ffe1e3180c0a029&ipo=images" alt="">
              {% comment %} </button> {% endcomment %}
            </div>
          {% else %}
            <div>
              <form action="{% url 'base:login' %}" method="POST" class="flex text-white text-sm">
                {% csrf_token %}
                <div class="flex justify-center align-center items-center">
                  <label for="first-name" class="text-sm font-semibold p-1">User Name</label>
                  <input
                    type="text"
                    name="username"
                    id="username"
                    class="rounded-md border-0 p-1 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600"
                  >
                </div>
                <div class="flex justify-center align-center items-center">
                  <label for="first-name" class="text-sm font-semibold p-1">Password</label>
                  <input
                    type="password"
                    name="password"
                    id="password"
                    class="rounded-md border-0 p-1 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600"
                  >
                </div>
                <form class="flex justify-center align-center items-center p-1">
                  <button type="submit" class="w-full rounded-md bg-indigo-600 px-3.5 py-2.5 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Log in</button>
                </form>
              </form>
            </div>
          {% endif %}
          </div>
        </div>
      </div>
    </div>
  </nav>
  <main class="w-8/12 ml-auto mr-auto pt-5">
    {% if request.GET.information %}
      <div class="bg-teal-100 border-t-4 border-teal-500 rounded-b text-teal-900 px-4 py-3 shadow-md" role="alert">
        <div class="flex">
          <div class="py-1"><svg class="fill-current h-6 w-6 text-teal-500 mr-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M2.93 17.07A10 10 0 1 1 17.07 2.93 10 10 0 0 1 2.93 17.07zm12.73-1.41A8 8 0 1 0 4.34 4.34a8 8 0 0 0 11.32 11.32zM9 11V9h2v6H9v-4zm0-6h2v2H9V5z"/></svg></div>
          <div>
            <p class="font-bold"> Information </p>
            <p class="text-sm">{{ request.GET.information }}</p>
          </div>
        </div>
      </div>
    {% endif %}
    <h2 class="text-2xl font-bold mt-10">
      Courses List
    </h2>
    <hr />
    {% if courses_list %}
    <ul role="list" class="divide-y divide-gray-100 shadow-md p-10 rounded-md">
      {% for course in courses_list  %}
      <li class="flex justify-between gap-x-6 py-5">
        <div class="flex min-w-0 gap-x-4">
          <img class="h-12 w-12 flex-none rounded-full bg-gray-50" src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ficon-library.com%2Fimages%2Fcourses-icon%2Fcourses-icon-27.jpg&f=1&nofb=1&ipt=4ae21b8868505c06482380b1845bacb474e463240f887108389fcefef86d6ecb&ipo=images" alt="">
          <div class="flex justify-center align-middle items-center">
            <p class="text-sm font-semibold leading-6 text-gray-900"> {{ course.title }} </p>
          </div>
        </div>
        <div class="hidden shrink-0 sm:flex sm:flex-col sm:items-end">
          {% if user.is_authenticated %}
          {% comment %} href="{% url 'base:exam_detail' %}?id={{ course.id }}" {% endcomment %}
            <a
              href="{% url 'base:course_detail' course.id %}"
              class="w-full rounded-md bg-indigo-600 px-3.5 py-2.5 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
            >Go to Details</a>
            {% comment %} <form action="{% url 'base:go_to_exam' %}" method="post">
              {% csrf_token %}
              <input type="hidden" name="id" value="{{ course.id }}">
              <button type="submit" class="w-full rounded-md bg-indigo-600 px-3.5 py-2.5 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Go to exam</button>
            </form> {% endcomment %}
          {% else %}
            <p class="text-xs text-red-800"> ( You must log in first ) </p>
            <button disabled="disabled" class="bg-gray-300 w-full rounded-md px-3.5 py-2.5 text-center text-sm font-semibold text-white shadow-sm">Go to exam</button>
          {% endif %}
        </div>
      </li>
      {% endfor %}
    </ul>
    {% else %}
    <div class="w-full flex justify-center align-middle items-center">
      <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative w-full" role="alert">
        <strong class="font-bold text-center">Ups...!</strong> <br />
        <span class="block sm:inline text-center">There are no courses available</span>
      </div>
    </div>
    {% endif %}
  </main>
</body>
</html>